# Generated by Django 4.2.9 on 2024-01-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='some_default_value', max_length=50, null=True)),
                ('password_admin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('langue', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero_de_telephone', models.IntegerField(blank=True, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password_avocat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
