# Generated by Django 4.2.9 on 2024-01-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_admin_avocat_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='some_default_value', max_length=50, null=True)),
                ('password_client', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
