# Generated by Django 4.2.9 on 2024-01-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='email',
            field=models.CharField(blank=True, default='some_default_value', max_length=50, null=True),
        ),
    ]
