# Generated by Django 3.2.5 on 2024-01-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20240125_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password_admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password_client',
        ),
    ]
