# Generated by Django 4.2.9 on 2024-01-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_avocat_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Avocat',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
