# Generated by Django 4.2.9 on 2024-01-03 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0005_delete_admin_delete_avocat_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='some_default_value', max_length=50, null=True)),
                ('password_admin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('avocat_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('langue', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero_de_telephone', models.IntegerField(blank=True, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password_avocat', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='some_default_value', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='some_default_value', max_length=50, null=True)),
                ('password_client', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id_creneau', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avocat_appointments', to='projet.avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='projet.client')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneau_appointments', to='projet.creneau')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.client')),
            ],
            options={
                'unique_together': {('client', 'avocat')},
            },
        ),
    ]
