# Generated by Django 4.2.9 on 2024-01-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_appointment',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
