# Generated by Django 4.2.9 on 2024-01-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_remove_appointment_id_appointment_id_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField()),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avocat_comments', to='projet.avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_comments', to='projet.client')),
            ],
        ),
    ]
